network:
 default:
   drive: bridge
   name: roboshop
   #external: true #I created network already using docker network create roboshop

volumes:
 mongodb:
 redis:
 mysql:
 rabbitmq: # docker volume create rabbitmq

services:
  mongodb:
   image: dinesh85/mongodb:v2
   container_name: mongodb
  volumes:
  - mongodb: /data/db

  catalogue:
  image: catalogue:v2
  container_name: catalogue
  depends_on:
   - mongodb
  
  redis:
  image: dinesh/redis:7.0
  container_name: redis
  volumes:
  - redis: /data

  user:
  image: user:v2
  container_name: user
  depends_on:
   - redis
   - mongodb

  cart:
  image: dinesh85/cart:v2
  container_name: cart
  depends_on:
   - redis
   - catalogue

  mysql:
  image: dinesh85/mysql:v2
  container_name: mysql
  volumes:
  -mysql: /var/lib/mysql

  shipping:
  image: dinesh85/shipping:v2
  container_name: shipping
  depends_on:
  - cart
  - mysql




